package com.rls.ids.controllers;

import com.rls.ids.constants.Role;
import com.rls.ids.constants.Status;
import com.rls.ids.exceptions.MissingHeaderException;
import com.rls.ids.exceptions.MissingRequiredFieldException;
import com.rls.ids.models.User;
import com.rls.ids.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/api/v1/user") // This means URL's start with /demo (after Application path)
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    @Autowired
    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @RequestMapping(path="", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public ResponseEntity<String> addNewUser(@RequestBody User user) {
//        checkValidation(user.getUserId());

        user.setRole(user.getRole().toLowerCase());
        user.setStatus(Status.DISABLED);
        userRepository.save(user);
        return new ResponseEntity<>("User saved successfully!", HttpStatus.OK);
    }

    @GetMapping(path="")
    public ResponseEntity<List<User>> getUsers(@RequestParam MultiValueMap<String, String> requestParams) {
        List result = userRepository.findAllPaged(requestParams);
        //noinspection unchecked
        return new ResponseEntity<List<User>>(result, HttpStatus.OK);
    }

    private void checkValidation(String userId) {
        if (userId == null || userId.isBlank())
            throw new MissingRequiredFieldException("user_id is missing or invalid.");
    }
}