server:
  port: 9090

spring:
  data:
    rest:
      default-media-type: "application/json;charset=UTF-8"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rlsstore
    username: rls
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        stat: debug